### ISSUE TITLE
the readme needs more instructions

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kardinal#72]
there is no way to install the project or to test it out; 

should we add a small section?

**Comment by skylarmb** [comment]
we removed a lot of the internal development instructions stuff that was in the readme to focus it on the info a customer would need to know. That said, we are lacking a quickstart guide on kardinal.dev/docs that would serve this purpose. 

I would still advocate separating instructions that are only for internal / development purposes to maybe a CONTRIBUTING.md file or something like that, instead of dumping it all into the main readme.

**Comment by h4ck3rk3y** [comment]
Thanks @tc87 this looks good :-)
